repos:
  - repo: local
    hooks:
      - id: ruff-check-uv-files
        name: Ruff Check (uv) on changed files
        entry: uv run ruff check --fix --exit-zero --respect-gitignore
        language: system
        types: [python]
        
      - id: ruff-format-uv-files
        name: Ruff Format (uv) on changed files
        entry: uv run ruff format --respect-gitignore
        language: system
        types: [python]        
