repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.1
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --exit-zero, --respect-gitignore, -s ]
    # Run the formatter.
    - id: ruff-format
      args: [ --exit-zero, --respect-gitignore, -s ]