services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
      - ./mlflow_data:/mlflow
    command: [
      "mlflow", "server",
      "--host", "0.0.0.0",
      "--port", "5000",
      "--backend-store-uri", "sqlite:////mlflow/mlflow.db",
      "--default-artifact-root", "/mlflow/artifacts",
      "--serve-artifacts"
    ]