"""init

Revision ID: 3daa3970ddc5
Revises:
Create Date: 2025-10-14 19:45:09.971378

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3daa3970ddc5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_celebrities_name"), table_name="celebrities", if_exists=True)
    op.drop_table("celebrities", if_exists=True)
    op.drop_table("inferences", if_exists=True)
    op.drop_index(op.f("ix_users_login"), table_name="users", if_exists=True)
    op.drop_table("users", if_exists=True)
    op.drop_table("inference_celebrities", if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    return
    # ### end Alembic commands ###
