"""add admin user

Revision ID: 3e12bcff6bf3
Revises: abdf719175f4
Create Date: 2025-10-19 21:04:29.581193

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

from src.config import config
from src.application.services import SecurityService

# revision identifiers, used by Alembic.
revision: str = "3e12bcff6bf3"
down_revision: Union[str, Sequence[str], None] = "abdf719175f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    hashed_pass = SecurityService.hash_password(config.auth.admin_password)
    op.execute(
        sa.text(
            "INSERT INTO users (name, password, role)VALUES (:name, :password, :role)"
        ).bindparams(name=config.auth.admin_name, password=hashed_pass, role="ADMIN")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("DELETE FROM users WHERE name = :name").bindparams(
            name=config.auth.admin_name
        )
    )  # ### end Alembic commands ###
