"""add tables

Revision ID: eacd7d53eb0b
Revises: 3daa3970ddc5
Create Date: 2025-10-14 19:48:13.173825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eacd7d53eb0b"
down_revision: Union[str, Sequence[str], None] = "3daa3970ddc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "celebrities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("picture", sa.LargeBinary(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_celebrities_name"), "celebrities", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_login"), "users", ["login"], unique=True)
    op.create_table(
        "inferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attractiveness", sa.Float(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("picture", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inference_celebrities",
        sa.Column("inference_id", sa.Integer(), nullable=False),
        sa.Column("celebrity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["celebrity_id"],
            ["celebrities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inference_id"],
            ["inferences.id"],
        ),
        sa.PrimaryKeyConstraint("inference_id", "celebrity_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inference_celebrities")
    op.drop_table("inferences")
    op.drop_index(op.f("ix_users_login"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_celebrities_name"), table_name="celebrities")
    op.drop_table("celebrities")
    # ### end Alembic commands ###
